### ISSUE TITLE
No fullscreen on mobile

### ISSUE THREAD

**Issue by smayton** [p34eu/jquery.full.screen#1]
Initiating via link acts as if the targeted content is opened then closed, i.e., on desktop if I don't style via onexit: function() {...} then I have inappropriately styled content once I esc fullscreen.

Any insight into getting this to work on iOS would be appreciated.

Seems to work on Chrome/Firefox on Android.

**Comment by p34eu** [comment]
Thanks, 
1. open/close issue should be fixed, you can try with the new version.
2. unfortunately iOS safari is not supported by the Full screen api, http://caniuse.com/#search=fullscreen
